#
# Makefile for the GalaxyCore touchscreen driver.
#
obj-$(CONFIG_TOUCHSCREEN_GCORE) += gcore_tp.o
gcore_tp-y	+=  gcore_drv_main.o
gcore_tp-y	+=  gcore_drv_qcom.o
gcore_tp-y	+=  gcore_drv_fw_update.o
gcore_tp-y	+=  gcore_drv_interface.o
gcore_tp-y	+=  gcore_drv_mp_test.o
