ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/sensorHub/inc_v1
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/hwmon/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/sensorHub/nanohub
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/1.0/situation
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/scp

obj-m	:=  lift_to_wake.o
