# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

obj-$(CONFIG_TYHX_HX9035)   += hx9035/
obj-$(CONFIG_INPUT_A96T376)    += A96T376/
obj-$(CONFIG_SX9328_SAR)     += sx9328_sar/
obj-$(CONFIG_HX9023S_SAR)     += hx9023_sar/
obj-$(CONFIG_SX9375_SAR)     += sx9375_sar/
obj-$(CONFIG_SX9338_SAR)     += sx9338_sar/
